In [1]:
import pandas as pd

df = pd.read_csv('traffic.csv')
df

,event,date,country,city,artist,album,track,isrc,linkid
0,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
1,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
2,click,2021-08-21,India,Ludhiana,Reyanna Maria,So Pretty,So Pretty,USUM72100871,23199824-9cf5-4b98-942a-34965c3b0cc2
3,click,2021-08-21,France,Unknown,"Simone & Simaria, Sebastian Yatra",No Llores Más,No Llores Más,BRUM72003904,35573248-4e49-47c7-af80-08a960fa74cd
4,click,2021-08-21,Maldives,Malé,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
...,...,...,...,...,...,...,...,...,...
226273,pageview,2021-08-24,Kuwait,Kuwait City,Sean Paul,The Trinity,Temperature,USAT20505520,04ba6b17-1055-4f0e-a75e-3cdb0d0d4106
226274,pageview,2021-08-24,India,Chennai,Miscél,when you left,when you left,QM42K1907890,2fc15e8b-83aa-40ee-9f9d-5d96c6d4356c
226275,pageview,2021-08-24,India,Jaipur,"Trippie Redd, Lil Uzi Vert",Holy Smokes (feat. Lil Uzi Vert),Holy Smokes,QZJ842001118,eedc8702-6bd2-499a-972f-260c35f72e0f
226276,pageview,2021-08-24,France,Unknown,Young Thug,Tick Tock,Tick Tock,USAT22104514,e0a76dc3-7ccd-405f-8ee8-a2c55c0e0ed2
226277,pageview,2021-08-24,Iraq,Duhok,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8

In [5]:
print(df[df['event']=='pageview'].shape)
df[df['event']=='pageview']\
  .groupby('date')\
  .agg(n_views = ('event','count'))

(142015, 9)

            n_views
date
2021-08-19    22366
2021-08-20    21382
2021-08-21    21349
2021-08-22    20430
2021-08-23    18646
2021-08-24    18693
2021-08-25    19149

In [8]:
df['event'].value_counts()

event
pageview    142015
click        55732
preview      28531
Name: count, dtype: int64

In [9]:
df[df['event']=='click']\
  .groupby('date')\
  .agg(n_views = ('event','count'))

            n_views
date
2021-08-19     9207
2021-08-20     8508
2021-08-21     8071
2021-08-22     7854
2021-08-23     7315
2021-08-24     7301
2021-08-25     7476

In [10]:
df[df['event']=='preview']\
  .groupby('date')\
  .agg(n_views = ('event','count'))

            n_views
date
2021-08-19     3788
2021-08-20     4222
2021-08-21     4663
2021-08-22     4349
2021-08-23     3847
2021-08-24     3840
2021-08-25     3822

In [12]:
df[df['event']=='pageview']\
  .groupby('country')\
  .agg(n_views = ('event','count'))\
  .sort_values(by='n_views', ascending=False)

                        n_views
country
Saudi Arabia              28873
India                     27286
United States             20839
France                     9674
Iraq                       4897
...                         ...
Principality of Monaco        1
Solomon Islands               1
Sint Maarten                  1
Saint Martin                  1
Wallis and Futuna             1

[211 rows x 1 columns]

In [14]:
print('click_rate', df[df['event']=='click'].shape[0]/df[df['event']=='pageview'].shape[0])

click_rate 0.3924374185825441

In [19]:
df1 = df[df['event']=='click'].groupby('linkid').agg(n_link_clicks = ('event','count'))
df2 = df[df['event']=='pageview'].groupby('linkid').agg(n_link_pageviews = ('event','count'))

df3 = pd.merge(df1, df2, how='inner', on='linkid')
df3['click_rate'] = df3['n_link_clicks']/df3['n_link_pageviews']
df3.sort_values(by='click_rate', ascending=False)

,n_link_clicks,n_link_pageviews,click_rate
linkid,,,
c95f1fc1-fab0-4c74-b3f5-52bd3684a713,923,10,92.300000
330773a6-f22a-5c7a-a3e4-7809fe8539b9,3,1,3.000000
27a91fe1-9fc0-5c28-9e9e-19ff0e7357a7,3,1,3.000000
f0996b01-0a9b-5a48-abbc-fa43a9e5dcdb,2,1,2.000000
efcbd6f1-1be5-5ffa-8082-f38189f02f0f,2,1,2.000000
...,...,...,...
5a5e88cd-fae9-4383-8b78-bf7f4e4f5fbd,1,8,0.125000
6e6c1939-9d37-450e-aec1-2af09140bc33,1,11,0.090909
899f223b-55f0-5f5a-8351-3ea64d0ce29f,1,11,0.090909
6dacffe9-779d-4e9b-94dd-a3e811b2983e,1,11,0.090909
229f278b-f052-57e7-813d-15d25f226723,1,11,0.090909

In [24]:
df4 = df[df['event']=='click'].groupby('linkid').agg(n_link_clicks = ('event','count'))
df5 = df[df['event']=='preview'].groupby('linkid').agg(n_link_previews = ('event','count'))

df6 = pd.merge(df4, df5, how='inner', on='linkid')


from scipy.stats import pearsonr

r, p_value = pearsonr(
    df6["n_link_clicks"],
    df6["n_link_previews"]
)

print("Pearson r:", r)
print("p-value:", p_value)


from scipy.stats import spearmanr

rho, p_value_spearman = spearmanr(
    df6["n_link_clicks"],
    df6["n_link_previews"]
)

print("\nSpearman rho:", rho)
print("p-value:", p_value_spearman)

Pearson r: 0.9934224704248963
p-value: 0.0

Spearman rho: 0.9260725903577562
p-value: 1.1377166697977484e-197